In [139]:
from repyability import *
%matplotlib inline

In [99]:
a = np.ones(20) * 3
a = np.random.weibull(a) * 100
a[1] = a[3]

In [218]:
cens = np.array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1] * 2)

In [191]:
cens

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1])

In [52]:
np.unique(a)

array([  50.45314932,   59.39804545,   61.21287018,   61.65018586,
         68.15239037,   84.874891  ,   89.16097159,  118.13142644,
        120.63003528])

In [58]:
np.sum(a[a==a[2]])

84.874891004342317

In [54]:
a==a[1]

array([False,  True, False,  True, False, False, False, False, False, False], dtype=bool)

In [55]:
a == 10

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [56]:
a

array([  61.65018586,  120.63003528,   84.874891  ,  120.63003528,
         50.45314932,   68.15239037,   59.39804545,   89.16097159,
         61.21287018,  118.13142644])